# To execute this docker compose yml file use `docker compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker compose -f docker-compose-v3.yml down`
version: "3"
services:
  selenium-hub:
    image: selenium/hub
    ports:
#      - "4442:4442"
#      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    env_file:
      - grid.env

  edge:
    image: selenium/node-edge
    shm_size: 2gb
    depends_on:
      - selenium-hub
    env_file:
      - grid.env